Add different roles
AY2425S1-CS2103T-T16-3/tp pull request #93
Opened 2024-10-16 14:17 UTC by zzzlou

Fixes #85

2024-10-16 16:05 UTC, Justin-Yeo requested changes
Overall looks good! Just some comments and clarifications 👍

2024-10-16 16:05 UTC, Justin-Yeo commented on src/main/java/seedu/address/model/person/PersonFactory.java
> +            throws CommandException {
Would an exception here be classified as CommandException or would it be another exception like IllegalArgumentException?

2024-10-16 16:05 UTC, Justin-Yeo commented on src/main/java/seedu/address/storage/JsonAdaptedPerson.java
> +        }
Are we able to SLAP this more?

2024-10-17 08:50 UTC, chongsun2002 commented on src/main/java/seedu/address/model/person/Date.java
> +    }
Lets create a separate method to do this, isValidDate should just return the validity of the string format.

2024-10-17 08:54 UTC, chongsun2002 commented on src/main/java/seedu/address/model/person/PersonFactory.java
> +        if (hours != null) {
If volunteers' hours is null, should just set it to 0

2024-10-17 10:56 UTC, merged